<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php
        echo "<title>My PHP Generated Page</title>";
    ?>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            min-height: 100vh;
            display: flex;
            flex-direction: column;
            background: #f5f5f5;
            color: #333;
        }

        header {
            background: #4F5B93;
            padding: 30px 20px;
            text-align: center;
        }

        header h1 {
            font-size: 2rem;
            color: #fff;
        }

        main {
            flex: 1;
            max-width: 800px;
            margin: 0 auto;
            padding: 30px 20px;
            width: 100%;
        }

        main p {
            background: #fff;
            padding: 15px 20px;
            margin: 15px 0;
            border-left: 4px solid #4F5B93;
        }

        footer {
            background: #fff;
            padding: 15px;
            text-align: center;
            color: #666;
            border-top: 1px solid #ddd;
        }

        nav {
            max-width: 800px;
            margin: 0 auto 20px;
            padding: 15px;
            background: #fff;
            text-align: center;
        }

        nav a {
            color: #4F5B93;
            text-decoration: none;
            margin: 0 15px;
        }

        nav a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <header>
        <h1>Welcome to My Website</h1>
    </header>

    <main>
        <?php
            echo "<p>This paragraph is generated by PHP.</p>";
        ?>

        <p>This paragraph is pure HTML.</p>

        <?php
            echo "<p>And we're back to PHP content!</p>";
            
            echo "<p>PHP and HTML can be mixed seamlessly.</p>";
        ?>
    </main>

    <nav>
        <a href="index.php">Home</a>
        <a href="exercise1.php">Exercise 1</a>
        <a href="exercise2.php">Exercise 2</a>
        <a href="exercise3.php">Exercise 3</a>
    </nav>

    <footer>
        <p>&copy; <?php echo date('Y'); ?> - Learning PHP</p>
    </footer>
</body>
</html>
